Feature/default license
LycheeOrg/Lychee-v3 pull request #125
Opened 2018-11-28 19:38 UTC by bennettscience

Changes to address #124. Needs review.

2018-11-29 08:21 UTC, ildyria requested changes
Before merging this, you need to make the PR on Lychee-front.
With this PR, Lychee-front won't be pointing to master anymore but the branch you created.

**Resolved, I did it.**

2018-11-29 08:34 UTC, ildyria requested changes

2018-11-29 08:34 UTC, ildyria commented on php/database/update_030206.php
> +
add the following query too:
```php
	$query = Database::prepare($connection, "ALTER TABLE `?` ALTER `license` SET DEFAULT 'none'", array(LYCHEE_TABLE_PHOTOS));
	$result = Database::execute($connection, $query, 'update_030206', __LINE__);
	if ($result===false) Response::error('Could not change default license value.');

this will make sure that initial value is indeed `none`

2018-11-29 08:34 UTC, ildyria commented on php/Modules/Photo.php
>  		$i = 0;
a bit later
`		$license = ($license == 'none' ? '' : $license);`
is not needed anymore as the default value is now `none`.

2018-11-29 13:47 UTC, bennettscience commented
Sorry, that turned into a mess. One day I'll do this without a thousand commit messages.

2018-11-29 14:12 UTC, LudovicRousseau commented
You can use `git rebase master` to cleanup a bit your branch.
And also play with git history (using `git rebase -i ...` or graphical tools) to merge 2 commits, etc.

2018-11-29 14:54 UTC, bennettscience commented
Yeah, I usually rebase, but I think I'm working with submodules incorrectly. I updated `Lychee-front` from @ildyria's commits, but then forgot to pull and commit in `Lychee`, so that threw a bunch of stuff off.

2018-11-30 12:21 UTC, merged

2018-11-30 12:22 UTC, ildyria commented
No worries. I cleaned it. :)