Feature/album license
LycheeOrg/Lychee-v3 pull request #139
Opened 2018-12-04 17:41 UTC by bennettscience

Updated for album-level licenses.

If you could pay particular attention to the license logic in the `Photo` module (lines 286-302) that would be helpful. In my testing, it's working correctly, but I want to make sure it's solid.

2018-12-04 22:50 UTC, ildyria requested changes
Please change the logic. Do not set the license on upload but on display.
This will simplify the logic when moving pictures from one album to another.

2018-12-04 22:50 UTC, ildyria commented on php/Modules/Photo.php
> +	public function add(array $files, $albumID, $returnOnError = false) {
Let the ` = 0` it is important. It is the default value for inserting a picture: the Unsorted album.

2018-12-04 22:50 UTC, ildyria commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
I don't think you should use strict equality (`===`) with '0' here. I would invert the two cases and make this a simple else:

```php
if ($albumID !== 0) {
...
} else {
...
}
```
not use a `else if` as this leaves and empty case here.

2018-12-04 22:50 UTC, ildyria commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
After further though. **DO NOT SET THE LICENSE ON UPLOAD**. Just set it to `'none'`.

The license should be shown when you **get** the picture.
The reason? It is way simpler to solve License consistency when you move a picture from an Album to another.

In other words, in the get you have to:
1. Check if there is a license set (`!= '' && != 'none'`) => pick that one.
2. If none, Check if the parent has a license set (`!= '' && != 'none'`) => pick that one.
3. if none, pick the default license of the installation.

2018-12-04 22:50 UTC, ildyria commented on php/Modules/Photo.php
> +			$info['aperture'], $info['make'], $info['model'], $info['lens'], $info['shutter'], $info['focal'], $info['takestamp'], $path_thumb, $albumID, $public, $star, $checksum, $medium, $small, $license);
`'none'` instead of `$license`

2018-12-04 22:50 UTC, ildyria commented on php/Modules/Photo.php
> +            $values = array(LYCHEE_TABLE_PHOTOS, $id, $info['title'], $photo_name, $file['type'], $info['size'], time(),  $path_thumb, $albumID, $public, $star, $checksum, $medium, $small, $license);
`'none'` instead of `$license`

2018-12-04 22:52 UTC, ildyria commented
Even if this is unpopular, during this update I would reset the license to default for all pictures.
The reason is to preserve help the consistency for the future. I don't think user will mind if they have only a setting to change (album or system wide) to display the correct license instead of changing it for every pictures again.

2018-12-04 23:23 UTC, d7415 commented
> Even if this is unpopular, during this update I would reset the license to default for all pictures.

Another option might be a "reset license for all photos" button in settings and a note in changelog.
I haven't decide whether such a button would be useful other than after this update though, and if not it's probably a bad idea (advanced users can change the db directly, but cluttering the UI for edge cases isn't great)

2018-12-04 23:27 UTC, ildyria commented
> I haven't decide whether such a button would be useful other than after this update though, and if not it's probably a bad idea (advanced users can change the db directly, but cluttering the UI for edge cases isn't great)

I can see the use case of a reset. (e.g. you forgot which photo has which rights)
But adding a search or something similar to smart albums for licenses (and tags) might also be a possibility for a longer term.

2018-12-05 00:18 UTC, bennettscience commented
Yeah, the button might be a bit too far just because it's for this single update...but noting it in the changelog so people are aware before updating is important.

I can't seem to keep track of when to PR lychee-front and when to just include it in this request 🤨

Would it be more helpful to PR there, close and reopen this one with the changes made?

2018-12-05 00:26 UTC, d7415 commented
Essentially if it affects Lychee-front, it needs to be updated there first, then the Lychee repo/pr can be pointed at the updated front end (and new dist/* can be generated)

2018-12-05 01:24 UTC, bennettscience commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
Shouldn't the license be set based on the global setting on upload? I was adding it to the Photos table so it _really is_ tagged with that license, not just displaying the settings in the photo view (metadata vs UI data layer). Is there a long-term benefit in differentiating between the two?

2018-12-05 07:37 UTC, ildyria commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
The long-term benefit is that you don't have to worry about the License setting on each picture, especially when you need to deal with functions such as *duplicate*, *move*, *merge*.

2018-12-05 07:51 UTC, ildyria commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
The other advantage of this approach can be seen in the following cases:
let's say the album is currently set to `License 1`, you uploads pictures in it.
- Case 1: you set the license of the picture as `License 1`.
- Case 2: or you set it to `none` and you display `License 1` when asked to see the picture.

Up until now you don't see the difference.
Now assume that you want to change the default license of the album to `License 2`
- in the case 1: you also need to update all the license of all the pictures in the album
- in the case 2: you don't need to update the licenses as it will be automatically taken care of on display.

Now assume that there was some pictures that had `License 3` set before your change from `License 2` to `License 3`.
- In case 1: you need to exclude them when you are updating the License of all the other pictures.
- In case 2: you don't need to bother with them.

Now assume that instead of switching to `License 2` you switched to `License 3` and now want to switch back to `License 1`.
- In case 1: even if you set the exclusion, the pictures that were initially under `License 3` you might have wanted to keep them as is. With this strategy, they will be switched to `License 1`. Once again an edge case.
- In case 2: once again you don't need to bother with them.

See why case 2 is suddenly more attractive ?

The goal of this approach is to reduce the number of changes you need to make to the database and facilitate changes when adding new functionalities so you don't have to think about edge cases all the time.

2018-12-06 02:41 UTC, bennettscience commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
Okay, all of those make sense. In #130, we had mentioned the following sequence: general settings < album setting < photo setting

With this, if a user sets a photo inside an album, the album license is shown _only if_ there is no specific license on the individual photo. Is that still the intended behavior? Or should every license be set at the album level only?

2018-12-06 03:33 UTC, ildyria commented on php/Modules/Photo.php
> +		if ($albumID === '0') {
> With this, if a user sets a photo inside an album, the album license is shown only if there is no specific license on the individual photo. Is that still the intended behavior? Or should every license be set at the album level only?

I would say that is the intended behavior. See more as treating special cases: when you want a specific license for a picture you set it yourself. Otherwise it follows the default order: *album license is visible* (or *general license is visible* if the album license is not set).

Note, it is the same for an Album, if the user want to set the album at a specific license, he set it. Otherwise the general license is *visible*.

2018-12-11 14:13 UTC, d7415 approved these changes

2018-12-11 14:36 UTC, ildyria approved these changes

2018-12-11 14:43 UTC, merged