Feature/photo desc
LycheeOrg/Lychee-v3 pull request #176
Opened 2019-01-29 19:24 UTC by bennettscience

Backend and database updates needed to implement #167.

2019-01-29 21:20 UTC, ildyria commented
I did not test it but this look correct to me.
Before merging we will need the PR in Lychee-front to be merged first. :+1:

2019-01-29 23:17 UTC, d7415 commented
> I did not test it but this look correct to me.

Ditto

> Before merging we will need the PR in Lychee-front to be merged first.

Agreed (for release process, as this takes us to 3.2.11)

2019-02-01 01:03 UTC, ildyria requested changes
Cf comment. Aside from that, it looks good to me.

2019-02-01 01:03 UTC, ildyria commented on php/database/update_030211.php
> +	$query 	= Database::prepare($connection, "INSERT INTO `?` (`key`, `value`) VALUES ('image_overlay_type_default', 'exif')", array(LYCHEE_TABLE_SETTINGS)))
`image_overlay_type_default` as a setting is not needed.

2019-02-01 01:24 UTC, ildyria approved these changes

2019-02-01 12:46 UTC, ildyria commented
Merged to v3.2.11-candidate.

2019-02-01 12:46 UTC, closed without merging