V3.2.11 candidate
LycheeOrg/Lychee-v3 pull request #183
Opened 2019-02-01 12:47 UTC by ildyria

Add different overlays: description and takestamp

Add unlimited time limit for import as an option => Use at your own risk

2019-02-01 17:44 UTC, bennettscience approved these changes

2019-02-01 18:20 UTC, d7415 requested changes
Overall looks good. A few queries. I haven't run it live yet (and need an early night so might not get around to it until tomorrow) but if you have that works for me.

2019-02-01 18:20 UTC, d7415 commented on php/Modules/Settings.php
> +		Log::error(Database::get(), __METHOD__, __LINE__, 'Could not update settings. Unknown overlay default.');
This looks redundant. Unless I'm missing something the error on line 222 should always have executed if this line is reached.

I wonder whether 221-228 could be refactored to look cleaner. Unfortunately I'm thinking in python at the moment (and haven't run this live yet), so I'm not sure whether this would work:
```php

		if ($found) {
			return (self::set('image_overlay_type', $imageOverlayType, true));
		}
		else {
			Log::error(Database::get(), __METHOD__, __LINE__, 'Could not update settings. Unknown overlay default.');
			return false;
		}
```
I left the `else` because I think it adds a little clarity...

2019-02-01 18:20 UTC, d7415 commented on php/database/update_030211.php
> +if (Database::setVersion($connection, 'update_030211')===false) Response::error('Could not update version of database!');
We should probably only set this if successful above?

2019-02-01 18:21 UTC, d7415 commented on php/Modules/Settings.php
> +		Log::error(Database::get(), __METHOD__, __LINE__, 'Could not update settings. Unknown overlay default.');
Well done on providing context, github...

2019-02-01 21:29 UTC, ildyria commented on php/database/update_030211.php
> +if (Database::setVersion($connection, 'update_030211')===false) Response::error('Could not update version of database!');
Nah it is fine, `Response::error()` is doing an `exit`.
https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Response.php

So any fail above will exit the update.

2019-02-02 04:36 UTC, d7415 commented on php/Modules/Settings.php
>  		if(!$found) {
This still seems backwards, but it's good enough for me :)

2019-02-02 04:37 UTC, d7415 approved these changes

2019-02-02 23:56 UTC, merged