Add usage of exiftool to get exif tags from camera manufactures
LycheeOrg/Lychee-v3 pull request #189
Opened 2019-02-10 23:34 UTC by mir07

Using exiftool for getting exif tags make available a lot more tags than the built-in functionality in PHP. Using exiftool will make eg. lens info available without having to rely on that users have exported a raw from Ligthroom.

Signed-off-by: Michael Rasmussen <mir@datanom.net>

2019-02-11 09:47 UTC, ildyria commented
Can you also add this PR to https://github.com/LycheeOrg/Lychee-laravel ?

And also make it such that it is the user who decides whether to use the php version of the system version.

2019-02-11 09:54 UTC, ildyria requested changes
Nice PR. I'm not really eager to add system calls but if this is something the user can willingly enable then I'm okay with it.

2019-02-11 09:54 UTC, ildyria commented on php/Modules/Photo.php
> +			system('which exiftool 2>&1 > /dev/null', $status);
This should be in Settings. In the same idea as https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Settings.php#L323

```php

	public static function hasImagick() {
		return (bool)(extension_loaded('imagick') && self::get()['imagick'] === '1');
	}
```

2019-02-11 14:17 UTC, mir07 commented
I have made the required changes. See next PR.

2019-02-11 14:25 UTC, ildyria requested changes
Thanks for the update. You might want to ditch the `public static function setUseExiftool($enable) {` function as this implies to also change the front end (Lychee-front).

A use can modify this value just by going to the advanced settings (and click "yes I understand the risks").

A database update file is required.

2019-02-11 14:25 UTC, ildyria commented on php/Modules/Photo.php
> +				if ($status == 0) {
This check:
```php
system('which exiftool 2>&1 > /dev/null', $status);
if ($status == 0) {
```
should be in the `Settings::useExiftool()`

2019-02-11 14:25 UTC, ildyria commented on php/Modules/Settings.php
> +        public static function setUseExiftool($enable) {
if you add this function then you must also define it's entry point in
https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php

2019-02-11 14:25 UTC, ildyria commented on php/Modules/Settings.php
> +        public static function setUseExiftool($enable) {
Also if you add it, you also need to add it in Lychee-front:
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/settings.js
and 
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/view.js

2019-02-11 14:25 UTC, ildyria commented on php/Modules/Settings.php
> +                return (bool) (self::get()['useExiftool'] === '1');
You also need to create a database update file to add this value, you can take example on:
https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030211.php
(but of course version 030212). :)

2019-02-11 14:26 UTC, mir07 commented
As can be seen I have prepared the code in such way that using exiftool can be changed on demand by the user when opening more in the settings dialog. Since using external tools is potential dangerous I have added a notice logging when using exiftool. Only thing missing is a database update script to add the new column 'useExiftool' to the database with the default configuration '0'.

2019-02-11 14:26 UTC, ildyria commented
> Since using external tools is potential dangerous I have added a notice logging when using exiftool.

I appreciate that. Good idea.

2019-02-11 14:30 UTC, mir07 commented on php/Modules/Settings.php
> +        public static function setUseExiftool($enable) {
I misunderstand this feature. I will drop the function setUseExiftool since making the changes under more is sufficient in my view.

2019-02-11 14:30 UTC, mir07 commented on php/Modules/Settings.php
> +                return (bool) (self::get()['useExiftool'] === '1');
Coming shortly ;-)

2019-02-11 15:00 UTC, ildyria approved these changes

2019-02-11 15:02 UTC, ildyria commented
Thanks a lot.
Can I trouble you to add the same thing to the version 4 (currently in alpha stages) ?
https://github.com/LycheeOrg/Lychee-laravel

2019-02-11 16:14 UTC, mir07 commented
Is it enough to make changes to this file 'Lychee-Laravel/app/Metadata/Extractor.php and 'Lychee-Laravel/app/Configs.php'?
Where should changes to database table lychee_settings be applied?

2019-02-11 16:16 UTC, ildyria commented
For the database you can do
```
php artisan make:migration name_of_the_migration
```
This will create a migration file in `database/migrations` : https://github.com/LycheeOrg/Lychee-Laravel/tree/master/database/migrations

For the content, you can have a look at: 
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/database/migrations/2019_02_01_122800_add_overlay_type.php

2019-02-11 22:41 UTC, mir07 commented
Hi,
I have tried installation of lychee-laravel but following the installation guide does not lead to a running installation. http://localhost simply displays the folder tree. http://localhost/public results in a crash:
[2019-02-11 22:31:38] local.ERROR: Call to undefined method App\Locale\Lang::get_locale() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Locale\\Lang::get_locale() at /var/www/app/Locale/Lang.php:38)
[stacktrace]
#0 /var/www/app/Http/Controllers/IndexController.php(14): App\\Locale\\Lang::get_lang(Object(App\\Configs))
#1 [internal function]: App\\Http\\Controllers\\IndexController->show()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\IndexController), 'show')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminat [...]

2019-02-12 11:59 UTC, ildyria commented
Can you please remove that last commit. This is unrelated to the current PR.

2019-02-12 12:05 UTC, d7415 commented
> Additionally, this is already provided by:
> https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php#L77

(instructions at [#134](https://github.com/LycheeOrg/Lychee/issues/134#issuecomment-443597023))

2019-02-12 12:06 UTC, d7415 commented
> Can you please remove that last commit. This is unrelated to the current PR.

This is the main issue with using master for PRs. I'm pretty sure you can't change branch without recreating the PR either :disappointed:

2019-02-12 12:23 UTC, mir07 commented
How can I push to my own branch again with out poluting here?

2019-02-12 12:26 UTC, ildyria commented
You will need to close this PR, then do:

```sh
# go back one commit without changing history on Master
git checkout HEAD^
# create a new branch "exiftool" here
git checkout -b exiftool
# push the new branch to your origin
git push origin exiftool
```
Then you can open a new PR between our master and your branch `exiftool`.

```sh
# go back to master
git checkout master
```

2019-02-12 12:27 UTC, merged

2019-02-12 12:29 UTC, ildyria commented
If you want to develop things without risking to pollute your master, the easiest way is to :
```sh
git checkout -b name_of_your_new_branch
git add # what ever you want to add
git commit # and your commit
git push origin name_of_your_new_branch
```

Before making a PR, it is usually a good idea to pull what is on the master and rebase your branch on it.

2019-02-12 12:35 UTC, mir07 commented
> Can you please remove that last commit. This is unrelated to the current PR.
> 
> Additionally, this is already provided by:
> https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php#L77
I was not aware of this. Is it documented somewhere?

2019-02-12 12:39 UTC, d7415 commented
> > Can you please remove that last commit. This is unrelated to the current PR.
> > Additionally, this is already provided by:
> > https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php#L77
> > I was not aware of this. Is it documented somewhere?

Only in the changelog and in that Issue. Reasoning being that it *should* only be required after an upgrade from before the `small`images were introduced.