prepare backend for #204
LycheeOrg/Lychee-v3 pull request #216
Opened 2019-02-24 08:38 UTC by guzzisti

I've  added the possibility room download small and medium size images.

Pull request for lychee-front is upcoming, need to do some testing first.

2019-02-24 18:10 UTC, ildyria requested changes
I pretty okay with all this changes. I would just like to highlight the fact that the download function has been removed from the v4 (as the user can just right click to download the picture.

Warning needs to be fixed.

2019-02-24 18:10 UTC, ildyria commented on php/Modules/Photo.php
> +			Log::error(Database::get(), __METHOD__, __LINE__, 'Original photo missing: ' .$fullfilepath);
This part of the warning should be changed: "Original photo"

2019-02-24 22:57 UTC, d7415 commented
> I would just like to highlight the fact that the download function has been removed from the v4 (as the user can just right click to download the picture.

On that basis, I have to wonder whether it would be simpler to go without the download function on either (at least for small/medium) as that would remove any need to change Lychee v3 - everything could be done in the front end and (presumably - I'm still not entirely comfortable with v4) be more consistent.

2019-02-25 12:17 UTC, guzzisti commented
I'm currently evaluating switching from Piwigo to Lychee, an easy download function for users to get full, medium or small sized photos would be vital to me.
How is a user supposed to get the links to medium and small sized versions of the picture?

2019-02-25 13:15 UTC, ildyria approved these changes

2019-02-25 16:03 UTC, mir07 commented
Could this be extended to also make download of the raw file available for download provided a method to upload raw files is available?

2019-02-25 20:16 UTC, guzzisti commented
@mir07 
This could be extended easily to support other formats as well (e.g. the thumbnail). The bigger part would be to allow raw file handling with Lychee. You should open a new issue for a discussion about this.

@ildyria @d7415 
I hope to send the pull request for the frontend tomorrow or on wednesday at the latest.

2019-02-27 11:51 UTC, ildyria commented
@guzzisti This is currently not implemented in Lychee v4 ( https://github.com/LycheeOrg/Lychee-Laravel/issues/95 ). If you want to do it, it would be a nice step for you to actually learn how the new architecture works. :)

2019-02-27 11:57 UTC, ildyria approved these changes
Looks good to me.

2019-02-27 12:01 UTC, merged

2019-02-27 12:18 UTC, guzzisti commented
@ildyria will have a look at the laravel implementation later.