Added video compatibility
LycheeOrg/Lychee-v3 pull request #74
Opened 2018-11-06 15:12 UTC by clementlamoureux

# Added video compatibility

- first version of video compatibility
- format accepted : **mp4**, **webm**, **ogv** (because of native browser player)
- thumbnails based on first frames of video, maybe have to be reworked later
- full width/height on screen
- :warning: SQL Database changes

![test](https://i.imgur.com/sd1gZhH.png)
![test](https://i.imgur.com/bEzL1Mg.png)

2018-11-06 16:10 UTC, ildyria requested changes
Really nice PR. :+1: 

Could you please update sql request (see bellow) so people already using Lychee can just do a `git pull` and everything works? Version number can be 030200. :)

2018-11-06 16:10 UTC, ildyria commented on php/database/photos_table.sql
> +  `type` varchar(15) NOT NULL,
This should not be placed here. Please create a migration file in `php/database` under the name `update_030200.php` to take care of that modification. Please have a look at https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030108.php for a template.

2018-11-06 16:10 UTC, ildyria commented on php/database/photos_table.sql
> +  `thumbUrl` char(43) NOT NULL,
this should not be placed here. See above.

2018-11-06 16:10 UTC, ildyria commented on php/Modules/Photo.php
> +            $values = array(LYCHEE_TABLE_PHOTOS, $id, $info['title'], $photo_name, $file['type'], $info['size'], time(),  '../../'.$photo_name, $albumID, $public, $star, $checksum, $medium);
Why is it a relative path `../../` ?

2018-11-06 17:06 UTC, merged

2018-11-07 16:10 UTC, d7415 commented
This is great! The [FAQ](https://github.com/LycheeOrg/Lychee/wiki/FAQ#can-i-upload-videos) needs updating though :slightly_smiling_face:

2018-11-14 00:53 UTC, bisherbas commented
I was able to upload an `mp4` file but the video is not playing.  See below.

![image](https://user-images.githubusercontent.com/42714627/48452595-ceb9a000-e77d-11e8-915b-e69992fa1292.png)

macOS and Firefox

2018-11-14 09:50 UTC, ildyria commented
@clementlamoureux Can you have a look ?

2018-11-14 23:12 UTC, d7415 commented
As a data point, this video (ffprobe output - looks similar) worked for me in Firefox and Chromium on Linux:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'out.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:05.01, start: 0.000000, bitrate: 6952 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 6704 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandle
```

@bisherbas If you load the video directly (outside of Lychee) does the browser play it?

2018-11-15 09:41 UTC, clementlamoureux commented
@bisherbas I think it's a browser compatiblity issue, as we are using native video element. I don't know what drivers are available on MacOS

2018-11-15 14:27 UTC, meminens commented
`Refused to load media from 'https://xxx.com/lychee/uploads/big/1238912123kjhadasd981231.mp4' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.`

It appears that this is the reason why video does not play. However, when I check my `apache2.conf` file I do not have a content security policy directive `"default-src 'none'"`. I am confused. HTTP header itself does not contain anything either.

Apache config:

`Header set Content-Security-Policy: "default-src 'self' media-src 'self' 'unsafe-inline' script-src 'self' 'unsafe-inline';"`

2018-11-15 14:39 UTC, d7415 commented
The .htaccess file sets it and has no media-src. I'll take a look later when I'm home unless someone beats me to it. Either add `media-src 'self';` there, delete/comment it, or change default-src from `'none'` to `'self'`

2018-11-15 15:01 UTC, bisherbas commented
Thanks for pointing me to the `.htaccess` file. After changing `default-src` from `none` to `self`, the video started playing immediately.